### ISSUE TITLE
Lista de Pedidos

### ISSUE THREAD

**Issue by anjelhm** [anjelhm/roundsmanApp#3]
- [x] Crear archivo Pedidos.js en la carpeta 
   contenedores.
- [x] Crear archivo ListaPedidos.js en la 
   carpeta Pedidos.
- [x] Crear la carpeta Pedidos dentro de la carpeta componentes.
- [x] El archivo Pedidos.js debe importar al 
   archivo ListaPedidos.js.
- [x] Importar el componente Pedidos al 
   componente Inicio en el View 1.
- [x] Dentro del archivo ListaPedidos crear 
   una lista apoyándose en el 
   componente ListView, ocupando 
  como item el componente 
  TarjetaPedido.

**Comment by GerardArHz** [comment]
La carpeta de pedidos debe estar en una carpeta en especifico o lo coloco en la carpeta src

**Comment by anjelhm** [comment]
Cierto se me olvido ponerle eso, deja lo corrijo

**Comment by GerardArHz** [comment]
ya subi el código de las tareas que me asignaste

**Comment by anjelhm** [comment]
@GerardArHz En la parte en la que importas Pedidos al View 1, borra la etiqueta ListaActual que también esta ahí, solo deja la etiqueta Pedidos

**Comment by GerardArHz** [comment]
@anjelhm ya quite la lista actual, antes de subir el cambio ahí algo mas en la cual tenga que corregir?

**Comment by anjelhm** [comment]
Ya está, solo falta que Óscar haga el componente TarjetaPedido y quedaría completado.

**Comment by ocarrizalmartinez** [comment]
:scream:
