### ISSUE TITLE
Pedidos actuales

### ISSUE THREAD

**Issue by anjelhm** [anjelhm/roundsmanApp#4]
- [x] Crear carpeta pedidosActuales dentro 
   de la carpeta componentes.
- [x] Crear archivo ListaActual.js dentro de 
   la carpeta pedidosActuales.
- [x] Crear el archivo PedidosActuales.js 
   dentro de la carpeta contenedores.
- [x] Importar el componente ListaActual 
  dentro del archivo PedidosActuales.
- [x] Crear una lista apoyándose en el 
   componente FlatList de react native.
- [x] Importar el componente 
   PedidosActuales dentro del archivo 
   Inicio.js en el View número 2.

**Comment by anjelhm** [comment]
Cualquier duda me la haces llegar por acá vale.

**Comment by ocarrizalmartinez** [comment]
El archivo ListaActual.js se repite con el que está en la carpeta ListaActual dentro de componentes

**Comment by ocarrizalmartinez** [comment]
¿Alguna otra opción?
